language: python
python:
  - "3.6"
sudo: required
dist: trusty
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
install:
  - pip install -r requirements.txt
before_script:
  - docker-compose up --build -d
  - sleep 30

script:
  - docker ps
  - python backend/tests/run.py -v

after_script:
  - docker-compose down
